### ISSUE TITLE
Faker not importing

### ISSUE THREAD

**Issue by mlgvla** [learn-co-curriculum/python-p4-hateoas-and-marshmallow#1]
### Canvas Link

https://learning.flatironschool.com/courses/6182/assignments/209739?module_item_id=483947

### Concern

Even though Faker seems to be in the Pipfile, I still had to import it - not sure why that is.

**Comment by Matt-Eva** [comment]
I had a different issue - I needed to add faker to the Pipfile, as it was absent when I first cloned down. Once I added it there and re-installed, everything was working as expected.

**Comment by mlgvla** [comment]
Actually, now that I think of it, I did install faker when I got the error message, and then everything worked. I never bothered to check the Pipfile -  I just assumed it was missing and fixed it on the spot. When I posted the issue, I double checked the Pipfile, and there it was…because I had installed it 🙄 Once you post an issue, you can’t delete it!!!

**Comment by professor-ben** [comment]
Another casualty of environment upgrades! This should be set now. Thanks for raising the issue!

-Ben
