### ISSUE TITLE
Issue in seed.py file

### ISSUE THREAD

**Issue by SWhalley1130** [learn-co-curriculum/python-p4-hateoas-and-marshmallow#3]
### Canvas Link

https://learning.flatironschool.com/courses/6267/assignments/236241?module_item_id=554241

### Concern

The extra `db.init_app(app)` on line 8 in seed.py prevents `python seed.py` from executing properly. 

![image](https://user-images.githubusercontent.com/98498031/230257293-75bd678b-fa64-4c4f-b0ee-27b939eb803f.png)

### Suggested Changes

Delete line 8 in seed.py

**Comment by pgill97** [comment]
Removed db.init_app(app) from seed and debug file.
