### ISSUE TITLE
seed.py

### ISSUE THREAD

**Issue by vargasmichael** [learn-co-curriculum/python-p4-hateoas-and-marshmallow#4]
### Canvas Link

https://learning.flatironschool.com/courses/6267/assignments/236241?module_item_id=554241

### Concern

I kept running into errors when attempting to run <python seed.py> after running <flask db upgrade>. 
This was the error. 

(python-p4-hateoas-and-marshmallow) vargas@Michaels-MacBook-Air server % python seed.py
Traceback (most recent call last):
  File "seed.py", line 8, in <module>
    db.init_app(app)
  File "/Users/vargas/.local/share/virtualenvs/python-p4-hateoas-and-marshmallow-POwEkDOD/lib/python3.8/site-packages/flask_sqlalchemy/extension.py", line 253, in init_app
    raise RuntimeError(
RuntimeError: A 'SQLAlchemy' instance has already been registered on this Flask app. Import and use that instance instead.

I commented out db.init_app(app) on line 8 of the seed.py and ran 
<python seed.py> and it executed with no issues. 

### Suggested Changes

Remove db.init_app(app) from the seed.py file.

**Comment by pgill97** [comment]
Removed db.init_app(app) from debug and seed file in both main and solution branches.
